const colorData = [
  { code: "#000000", name: "Black" },
  { code: "#0C090A", name: "Night" },
  { code: "#34282C", name: "Charcoal" },
  { code: "#3B3131", name: "Oil" },
  { code: "#3A3B3C", name: "Dark Gray" },
  { code: "#454545", name: "Light Black" },
  { code: "#413839", name: "Black Cat" },
  { code: "#3D3C3A", name: "Iridium" },
  { code: "#463E3F", name: "Black Eel" },
  { code: "#4C4646", name: "Black Cow" },
  { code: "#504A4B", name: "Gray Wolf" },
  { code: "#565051", name: "Vampire Gray" },
  { code: "#52595D", name: "Iron Gray" },
  { code: "#5C5858", name: "Gray Dolphin" },
  { code: "#625D5D", name: "Carbon Gray" },
  { code: "#666362", name: "Ash Gray" },
  { code: "#696969", name: "DimGray or DimGrey" },
  { code: "#686A6C", name: "Nardo Gray" },
  { code: "#6D6968", name: "Cloudy Gray" },
  { code: "#726E6D", name: "Smokey Gray" },
  { code: "#736F6E", name: "Alien Gray" },
  { code: "#757575", name: "Sonic Silver" },
  { code: "#797979", name: "Platinum Gray" },
  { code: "#837E7C", name: "Granite" },
  { code: "#808080", name: "Gray or Grey" },
  { code: "#848482", name: "Battleship Gray" },
  { code: "#8D918D", name: "Gunmetal Gray" },
  { code: "#A9A9A9", name: "DarkGray or DarkGrey" },
  { code: "#B6B6B4", name: "Gray Cloud" },
  { code: "#C0C0C0", name: "Silver" },
  { code: "#C9C0BB", name: "Pale Silver" },
  { code: "#D1D0CE", name: "Gray Goose" },
  { code: "#CECECE", name: "Platinum Silver" },
  { code: "#D3D3D3", name: "LightGray or LightGrey" },
  { code: "#DADBDD", name: "Silver White" },
  { code: "#DCDCDC", name: "Gainsboro" },
  { code: "#E5E4E2", name: "Platinum" },
  { code: "#BCC6CC", name: "Metallic Silver" },
  { code: "#98AFC7", name: "Blue Gray" },
  { code: "#838996", name: "Roman Silver" },
  {
    code: "#778899",
    name: "LightSlateGray or LightSlateGrey",
  },
  { code: "#708090", name: "SlateGray or SlateGrey" },
  { code: "#6D7B8D", name: "Rat Gray" },
  { code: "#657383", name: "Slate Granite Gray" },
  { code: "#616D7E", name: "Jet Gray" },
  { code: "#646D7E", name: "Mist Blue" },
  { code: "#566D7E", name: "Marble Blue" },
  { code: "#737CA1", name: "Slate Blue Grey" },
  { code: "#728FCE", name: "Light Purple Blue" },
  { code: "#4863A0", name: "Azure Blue" },
  { code: "#2B547E", name: "Blue Jay" },
  { code: "#36454F", name: "Charcoal Blue" },
  { code: "#29465B", name: "Dark Blue Grey" },
  { code: "#2B3856", name: "Dark Slate" },
  { code: "#123456", name: "Deep-Sea Blue" },
  { code: "#151B54", name: "Night Blue" },
  { code: "#191970", name: "MidnightBlue" },
  { code: "#000080", name: "Navy" },
  { code: "#151B8D", name: "Denim Dark Blue" },
  { code: "#00008B", name: "DarkBlue" },
  { code: "#15317E", name: "Lapis Blue" },
  { code: "#0000A0", name: "New Midnight Blue" },
  { code: "#0000A5", name: "Earth Blue" },
  { code: "#0020C2", name: "Cobalt Blue" },
  { code: "#0000CD", name: "MediumBlue" },
  { code: "#0041C2", name: "Blueberry Blue" },
  { code: "#2916F5", name: "Canary Blue" },
  { code: "#0000FF", name: "Blue" },
  { code: "#0002FF", name: "Samco Blue" },
  { code: "#0909FF", name: "Bright Blue" },
  { code: "#1F45FC", name: "Blue Orchid" },
  { code: "#2554C7", name: "Sapphire Blue" },
  { code: "#1569C7", name: "Blue Eyes" },
  { code: "#1974D2", name: "Bright Navy Blue" },
  { code: "#2B60DE", name: "Balloon Blue" },
  { code: "#4169E1", name: "RoyalBlue" },
  { code: "#2B65EC", name: "Ocean Blue" },
  { code: "#306EFF", name: "Blue Ribbon" },
  { code: "#157DEC", name: "Blue Dress" },
  { code: "#1589FF", name: "Neon Blue" },
  { code: "#1E90FF", name: "DodgerBlue" },
  { code: "#368BC1", name: "Glacial Blue Ice" },
  { code: "#4682B4", name: "SteelBlue" },
  { code: "#488AC7", name: "Silk Blue" },
  { code: "#357EC7", name: "Windows Blue" },
  { code: "#3090C7", name: "Blue Ivy" },
  { code: "#659EC7", name: "Blue Koi" },
  { code: "#87AFC7", name: "Columbia Blue" },
  { code: "#95B9C7", name: "Baby Blue" },
  { code: "#6495ED", name: "CornflowerBlue" },
  { code: "#6698FF", name: "Sky Blue Dress" },
  { code: "#56A5EC", name: "Iceberg" },
  { code: "#38ACEC", name: "Butterfly Blue" },
  { code: "#00BFFF", name: "DeepSkyBlue" },
  { code: "#3BB9FF", name: "Midday Blue" },
  { code: "#5CB3FF", name: "Crystal Blue" },
  { code: "#79BAEC", name: "Denim Blue" },
  { code: "#82CAFF", name: "Day Sky Blue" },
  { code: "#87CEFA", name: "LightSkyBlue" },
  { code: "#87CEEB", name: "SkyBlue" },
  { code: "#A0CFEC", name: "Jeans Blue" },
  { code: "#B7CEEC", name: "Blue Angel" },
  { code: "#B4CFEC", name: "Pastel Blue" },
  { code: "#ADDFFF", name: "Light Day Blue" },
  { code: "#C2DFFF", name: "Sea Blue" },
  { code: "#C6DEFF", name: "Heavenly Blue" },
  { code: "#BDEDFF", name: "Robin Egg Blue" },
  { code: "#B0E0E6", name: "PowderBlue" },
  { code: "#AFDCEC", name: "Coral Blue" },
  { code: "#ADD8E6", name: "LightBlue" },
  { code: "#B0CFDE", name: "LightSteelBlue" },
  { code: "#C9DFEC", name: "Gulf Blue" },
  { code: "#D5D6EA", name: "Pastel Light Blue" },
  { code: "#E3E4FA", name: "Lavender Blue" },
  { code: "#DBE9FA", name: "White Blue" },
  { code: "#E6E6FA", name: "Lavender" },
  { code: "#EBF4FA", name: "Water" },
  { code: "#F0F8FF", name: "AliceBlue" },
  { code: "#F8F8FF", name: "GhostWhite" },
  { code: "#F0FFFF", name: "Azure" },
  { code: "#E0FFFF", name: "LightCyan" },
  { code: "#CCFFFF", name: "Light Slate" },
  { code: "#9AFEFF", name: "Electric Blue" },
  { code: "#7DFDFE", name: "Tron Blue" },
  { code: "#57FEFF", name: "Blue Zircon" },
  { code: "#00FFFF", name: "Aqua or Cyan" },
  { code: "#0AFFFF", name: "Bright Cyan" },
  { code: "#50EBEC", name: "Celeste" },
  { code: "#4EE2EC", name: "Blue Diamond" },
  { code: "#16E2F5", name: "Bright Turquoise" },
  { code: "#8EEBEC", name: "Blue Lagoon" },
  { code: "#AFEEEE", name: "PaleTurquoise" },
  { code: "#CFECEC", name: "Pale Blue Lily" },
  { code: "#B3D9D9", name: "Light Teal" },
  { code: "#81D8D0", name: "Tiffany Blue" },
  { code: "#77BFC7", name: "Blue Hosta" },
  { code: "#92C7C7", name: "Cyan Opaque" },
  { code: "#78C7C7", name: "Northern Lights Blue" },
  { code: "#7BCCB5", name: "Blue Green" },
  { code: "#66CDAA", name: "MediumAquaMarine" },
  { code: "#AAF0D1", name: "Magic Mint" },
  { code: "#93FFE8", name: "Light Aquamarine" },
  { code: "#7FFFD4", name: "Aquamarine" },
  { code: "#01F9C6", name: "Bright Teal" },
  { code: "#40E0D0", name: "Turquoise" },
  { code: "#48D1CC", name: "MediumTurquoise" },
  { code: "#48CCCD", name: "Deep Turquoise" },
  { code: "#46C7C7", name: "Jellyfish" },
  { code: "#43C6DB", name: "Blue Turquoise" },
  { code: "#00CED1", name: "DarkTurquoise" },
  { code: "#43BFC7", name: "Macaw Blue Green" },
  { code: "#20B2AA", name: "LightSeaGreen" },
  { code: "#3EA99F", name: "Seafoam Green" },
  { code: "#5F9EA0", name: "CadetBlue" },
  { code: "#3B9C9C", name: "Deep-Sea" },
  { code: "#008B8B", name: "DarkCyan" },
  { code: "#00827F", name: "Teal Green" },
  { code: "#008080", name: "Teal" },
  { code: "#007C80", name: "Teal Blue" },
  { code: "#045F5F", name: "Medium Teal" },
  { code: "#045D5D", name: "Dark Teal" },
  { code: "#033E3E", name: "Deep Teal" },
  {
    code: "#25383C",
    name: "DarkSlateGray or DarkSlateGrey",
  },
  { code: "#2C3539", name: "Gunmetal" },
  { code: "#3C565B", name: "Blue Moss Green" },
  { code: "#4C787E", name: "Beetle Green" },
  { code: "#5E7D7E", name: "Grayish Turquoise" },
  { code: "#307D7E", name: "Greenish Blue" },
  { code: "#348781", name: "Aquamarine Stone" },
  { code: "#438D80", name: "Sea Turtle Green" },
  { code: "#4E8975", name: "Dull-Sea Green" },
  { code: "#1F6357", name: "Dark Green Blue" },
  { code: "#306754", name: "Deep-Sea Green" },
  { code: "#006A4E", name: "Bottle Green" },
  { code: "#2E8B57", name: "SeaGreen" },
  { code: "#1B8A6B", name: "Elf Green" },
  { code: "#31906E", name: "Dark Mint" },
  { code: "#00A36C", name: "Jade" },
  { code: "#34A56F", name: "Earth Green" },
  { code: "#1AA260", name: "Chrome Green" },
  { code: "#50C878", name: "Emerald" },
  { code: "#3EB489", name: "Mint" },
  { code: "#3CB371", name: "MediumSeaGreen" },
  { code: "#7C9D8E", name: "Metallic Green" },
  { code: "#78866B", name: "Camouflage Green" },
  { code: "#848B79", name: "Sage Green" },
  { code: "#617C58", name: "Hazel Green" },
  { code: "#728C00", name: "Venom Green" },
  { code: "#6B8E23", name: "OliveDrab" },
  { code: "#808000", name: "Olive" },
  { code: "#556B2F", name: "DarkOliveGreen" },
  { code: "#4E5B31", name: "Military Green" },
  { code: "#3A5F0B", name: "Green Leaves" },
  { code: "#4B5320", name: "Army Green" },
  { code: "#667C26", name: "Fern Green" },
  { code: "#4E9258", name: "Fall Forest Green" },
  { code: "#08A04B", name: "Irish Green" },
  { code: "#387C44", name: "Pine Green" },
  { code: "#347235", name: "Medium Forest Green" },
  { code: "#347C2C", name: "Jungle Green" },
  { code: "#227442", name: "Cactus Green" },
  { code: "#228B22", name: "ForestGreen" },
  { code: "#008000", name: "Green" },
  { code: "#006400", name: "DarkGreen" },
  { code: "#056608", name: "Deep Green" },
  { code: "#046307", name: "Deep Emerald Green" },
  { code: "#355E3B", name: "Hunter Green" },
  { code: "#254117", name: "Dark Forest Green" },
  { code: "#004225", name: "Lotus Green" },
  { code: "#437C17", name: "Seaweed Green" },
  { code: "#347C17", name: "Shamrock Green" },
  { code: "#6AA121", name: "Green Onion" },
  { code: "#8A9A5B", name: "Moss Green" },
  { code: "#3F9B0B", name: "Grass Green" },
  { code: "#4AA02C", name: "Green Pepper" },
  { code: "#41A317", name: "Dark Lime Green" },
  { code: "#12AD2B", name: "Parrot Green" },
  { code: "#3EA055", name: "Clover Green" },
  { code: "#73A16C", name: "Dinosaur Green" },
  { code: "#6CBB3C", name: "Green Snake" },
  { code: "#6CC417", name: "Alien Green" },
  { code: "#4CC417", name: "Green Apple" },
  { code: "#32CD32", name: "LimeGreen" },
  { code: "#52D017", name: "Pea Green" },
  { code: "#4CC552", name: "Kelly Green" },
  { code: "#54C571", name: "Zombie Green" },
  { code: "#89C35C", name: "Green Peas" },
  { code: "#85BB65", name: "Dollar Bill Green" },
  { code: "#99C68E", name: "Frog Green" },
  { code: "#A0D6B4", name: "Turquoise Green" },
  { code: "#8FBC8F", name: "DarkSeaGreen" },
  { code: "#829F82", name: "Basil Green" },
  { code: "#A2AD9C", name: "Gray Green" },
  { code: "#9CB071", name: "Iguana Green" },
  { code: "#8FB31D", name: "Citron Green" },
  { code: "#B0BF1A", name: "Acid Green" },
  { code: "#B2C248", name: "Avocado Green" },
  { code: "#9DC209", name: "Pistachio Green" },
  { code: "#A1C935", name: "Salad Green" },
  { code: "#9ACD32", name: "YellowGreen" },
  { code: "#77DD77", name: "Pastel Green" },
  { code: "#7FE817", name: "Hummingbird Green" },
  { code: "#59E817", name: "Nebula Green" },
  { code: "#57E964", name: "Stoplight Go Green" },
  { code: "#16F529", name: "Neon Green" },
  { code: "#5EFB6E", name: "Jade Green" },
  { code: "#36F57F", name: "Lime Mint Green" },
  { code: "#00FF7F", name: "SpringGreen" },
  { code: "#00FA9A", name: "MediumSpringGreen" },
  { code: "#5FFB17", name: "Emerald Green" },
  { code: "#00FF00", name: "Lime" },
  { code: "#7CFC00", name: "LawnGreen" },
  { code: "#66FF00", name: "Bright Green" },
  { code: "#7FFF00", name: "Chartreuse" },
  { code: "#87F717", name: "Yellow Lawn Green" },
  { code: "#98F516", name: "Aloe Vera Green" },
  { code: "#B1FB17", name: "Dull Green Yellow" },
  { code: "#ADF802", name: "Lemon Green" },
  { code: "#ADFF2F", name: "GreenYellow" },
  { code: "#BDF516", name: "Chameleon Green" },
  { code: "#DAEE01", name: "Neon Yellow Green" },
  { code: "#E2F516", name: "Yellow Green Grosbeak" },
  { code: "#CCFB5D", name: "Tea Green" },
  { code: "#BCE954", name: "Slime Green" },
  { code: "#64E986", name: "Algae Green" },
  { code: "#90EE90", name: "LightGreen" },
  { code: "#6AFB92", name: "Dragon Green" },
  { code: "#98FB98", name: "PaleGreen" },
  { code: "#98FF98", name: "Mint Green" },
  { code: "#B5EAAA", name: "Green Thumb" },
  { code: "#E3F9A6", name: "Organic Brown" },
  { code: "#C3FDB8", name: "Light Jade" },
  { code: "#C2E5D3", name: "Light Mint Green" },
  { code: "#DBF9DB", name: "Light Rose Green" },
  { code: "#E8F1D4", name: "Chrome White" },
  { code: "#F0FFF0", name: "HoneyDew" },
  { code: "#F5FFFA", name: "MintCream" },
  { code: "#FFFACD", name: "LemonChiffon" },
  { code: "#FFFFC2", name: "Parchment" },
  { code: "#FFFFCC", name: "Cream" },
  { code: "#FFFDD0", name: "Cream White" },
  { code: "#FAFAD2", name: "LightGoldenRodYellow" },
  { code: "#FFFFE0", name: "LightYellow" },
  { code: "#F5F5DC", name: "Beige" },
  { code: "#FFF8DC", name: "Cornsilk" },
  { code: "#FBF6D9", name: "Blonde" },
  { code: "#F7E7CE", name: "Champagne" },
  { code: "#FAEBD7", name: "AntiqueWhite" },
  { code: "#FFEFD5", name: "PapayaWhip" },
  { code: "#FFEBCD", name: "BlanchedAlmond" },
  { code: "#FFE4C4", name: "Bisque" },
  { code: "#F5DEB3", name: "Wheat" },
  { code: "#FFE4B5", name: "Moccasin" },
  { code: "#FFE5B4", name: "Peach" },
  { code: "#FED8B1", name: "Light Orange" },
  { code: "#FFDAB9", name: "PeachPuff" },
  { code: "#FBD5AB", name: "Coral Peach" },
  { code: "#FFDEAD", name: "NavajoWhite" },
  { code: "#FBE7A1", name: "Golden Blonde" },
  { code: "#F3E3C3", name: "Golden Silk" },
  { code: "#F0E2B6", name: "Dark Blonde" },
  { code: "#F1E5AC", name: "Light Gold" },
  { code: "#F3E5AB", name: "Vanilla" },
  { code: "#ECE5B6", name: "Tan Brown" },
  { code: "#E8E4C9", name: "Dirty White" },
  { code: "#EEE8AA", name: "PaleGoldenRod" },
  { code: "#F0E68C", name: "Khaki" },
  { code: "#EDDA74", name: "Cardboard Brown" },
  { code: "#EDE275", name: "Harvest Gold" },
  { code: "#FFE87C", name: "Sun Yellow" },
  { code: "#FFF380", name: "Corn Yellow" },
  { code: "#FAF884", name: "Pastel Yellow" },
  { code: "#FFFF33", name: "Neon Yellow" },
  { code: "#FFFF00", name: "Yellow" },
  { code: "#FFEF00", name: "Canary Yellow" },
  { code: "#F5E216", name: "Banana Yellow" },
  { code: "#FFDB58", name: "Mustard Yellow" },
  { code: "#FFDF00", name: "Golden Yellow" },
  { code: "#F9DB24", name: "Bold Yellow" },
  { code: "#FFD801", name: "Rubber Ducky Yellow" },
  { code: "#FFD700", name: "Gold" },
  { code: "#FDD017", name: "Bright Gold" },
  { code: "#FFCE44", name: "Chrome Gold" },
  { code: "#EAC117", name: "Golden Brown" },
  { code: "#F6BE00", name: "Deep Yellow" },
  { code: "#F2BB66", name: "Macaroni and Cheese" },
  { code: "#FBB917", name: "Saffron" },
  { code: "#FDBD01", name: "Neon Gold" },
  { code: "#FBB117", name: "Beer" },
  {
    code: "#FFAE42",
    name: "Yellow Orange or Orange Yellow",
  },
  { code: "#FFA62F", name: "Cantaloupe" },
  { code: "#FFA600", name: "Cheese Orange" },
  { code: "#FFA500", name: "Orange" },
  { code: "#EE9A4D", name: "Brown Sand" },
  { code: "#F4A460", name: "SandyBrown" },
  { code: "#E2A76F", name: "Brown Sugar" },
  { code: "#C19A6B", name: "Camel Brown" },
  { code: "#E6BF83", name: "Deer Brown" },
  { code: "#DEB887", name: "BurlyWood" },
  { code: "#D2B48C", name: "Tan" },
  { code: "#C8AD7F", name: "Light French Beige" },
  { code: "#C2B280", name: "Sand" },
  { code: "#BCB88A", name: "Sage" },
  { code: "#C8B560", name: "Fall Leaf Brown" },
  { code: "#C9BE62", name: "Ginger Brown" },
  { code: "#C9AE5D", name: "Bronze Gold" },
  { code: "#BDB76B", name: "DarkKhaki" },
  { code: "#BAB86C", name: "Olive Green" },
  { code: "#B5A642", name: "Brass" },
  { code: "#C7A317", name: "Cookie Brown" },
  { code: "#D4AF37", name: "Metallic Gold" },
  { code: "#E9AB17", name: "Bee Yellow" },
  { code: "#E8A317", name: "School Bus Yellow" },
  { code: "#DAA520", name: "GoldenRod" },
  { code: "#D4A017", name: "Orange Gold" },
  { code: "#C68E17", name: "Caramel" },
  { code: "#B8860B", name: "DarkGoldenRod" },
  { code: "#C58917", name: "Cinnamon" },
  { code: "#CD853F", name: "Peru" },
  { code: "#CD7F32", name: "Bronze" },
  { code: "#C88141", name: "Tiger Orange" },
  { code: "#B87333", name: "Copper" },
  { code: "#AA6C39", name: "Dark Gold" },
  { code: "#A97142", name: "Metallic Bronze" },
  { code: "#AB784E", name: "Dark Almond" },
  { code: "#966F33", name: "Wood" },
  { code: "#806517", name: "Oak Brown" },
  { code: "#665D1E", name: "Antique Bronze" },
  { code: "#8E7618", name: "Hazel" },
  { code: "#8B8000", name: "Dark Yellow" },
  { code: "#827839", name: "Dark Moccasin" },
  { code: "#8A865D", name: "Khaki Green" },
  { code: "#93917C", name: "Millennium Jade" },
  { code: "#9F8C76", name: "Dark Beige" },
  { code: "#AF9B60", name: "Bullet Shell" },
  { code: "#827B60", name: "Army Brown" },
  { code: "#786D5F", name: "Sandstone" },
  { code: "#483C32", name: "Taupe" },
  { code: "#493D26", name: "Mocha" },
  { code: "#513B1C", name: "Milk Chocolate" },
  { code: "#3D3635", name: "Gray Brown" },
  { code: "#3B2F2F", name: "Dark Coffee" },
  { code: "#43302E", name: "Old Burgundy" },
  { code: "#49413F", name: "Western Charcoal" },
  { code: "#5C3317", name: "Bakers Brown" },
  { code: "#654321", name: "Dark Brown" },
  { code: "#704214", name: "Sepia Brown" },
  { code: "#804A00", name: "Dark Bronze" },
  { code: "#6F4E37", name: "Coffee" },
  { code: "#835C3B", name: "Brown Bear" },
  { code: "#7F5217", name: "Red Dirt" },
  { code: "#7F462C", name: "Sepia" },
  { code: "#A0522D", name: "Sienna" },
  { code: "#8B4513", name: "SaddleBrown" },
  { code: "#8A4117", name: "Dark Sienna" },
  { code: "#7E3817", name: "Sangria" },
  { code: "#7E3517", name: "Blood Red" },
  { code: "#954535", name: "Chestnut" },
  { code: "#9E4638", name: "Coral Brown" },
  { code: "#C34A2C", name: "Chestnut Red" },
  { code: "#C04000", name: "Mahogany" },
  { code: "#EB5406", name: "Red Gold" },
  { code: "#C35817", name: "Red Fox" },
  { code: "#B86500", name: "Dark Bisque" },
  { code: "#B5651D", name: "Light Brown" },
  { code: "#B76734", name: "Petra Gold" },
  { code: "#C36241", name: "Rust" },
  { code: "#CB6D51", name: "Copper Red" },
  { code: "#C47451", name: "Orange Salmon" },
  { code: "#D2691E", name: "Chocolate" },
  { code: "#CC6600", name: "Sedona" },
  { code: "#E56717", name: "Papaya Orange" },
  { code: "#E66C2C", name: "Halloween Orange" },
  { code: "#FF6700", name: "Neon Orange" },
  { code: "#FF5F1F", name: "Bright Orange" },
  { code: "#F87217", name: "Pumpkin Orange" },
  { code: "#F88017", name: "Carrot Orange" },
  { code: "#FF8C00", name: "DarkOrange" },
  {
    code: "#F87431",
    name: "Construction Cone Orange",
  },
  { code: "#FF7722", name: "Indian Saffron" },
  { code: "#E67451", name: "Sunrise Orange" },
  { code: "#FF8040", name: "Mango Orange" },
  { code: "#FF7F50", name: "Coral" },
  { code: "#F88158", name: "Basket Ball Orange" },
  { code: "#F9966B", name: "Light Salmon Rose" },
  { code: "#FFA07A", name: "LightSalmon" },
  { code: "#E9967A", name: "DarkSalmon" },
  { code: "#E78A61", name: "Tangerine" },
  { code: "#DA8A67", name: "Light Copper" },
  { code: "#FF8674", name: "Salmon Pink" },
  { code: "#FA8072", name: "Salmon" },
  { code: "#F98B88", name: "Peach Pink" },
  { code: "#F08080", name: "LightCoral" },
  { code: "#F67280", name: "Pastel Red" },
  { code: "#E77471", name: "Pink Coral" },
  { code: "#F75D59", name: "Bean Red" },
  { code: "#E55451", name: "Valentine Red" },
  { code: "#CD5C5C", name: "IndianRed" },
  { code: "#FF6347", name: "Tomato" },
  { code: "#E55B3C", name: "Shocking Orange" },
  { code: "#FF4500", name: "OrangeRed" },
  { code: "#FF0000", name: "Red" },
  { code: "#FD1C03", name: "Neon Red" },
  { code: "#FF2400", name: "Scarlet Red" },
  { code: "#F62217", name: "Ruby Red" },
  { code: "#F70D1A", name: "Ferrari Red" },
  { code: "#F62817", name: "Fire Engine Red" },
  { code: "#E42217", name: "Lava Red" },
  { code: "#E41B17", name: "Love Red" },
  { code: "#DC381F", name: "Grapefruit" },
  { code: "#C24641", name: "Cherry Red" },
  { code: "#C11B17", name: "Chilli Pepper" },
  { code: "#B22222", name: "FireBrick" },
  { code: "#B21807", name: "Tomato Sauce Red" },
  { code: "#A52A2A", name: "Brown" },
  { code: "#A70D2A", name: "Carbon Red" },
  { code: "#9F000F", name: "Cranberry" },
  { code: "#931314", name: "Saffron Red" },
  { code: "#990000", name: "Crimson Red" },
  { code: "#990012", name: "Red Wine or Wine Red" },
  { code: "#8B0000", name: "DarkRed" },
  { code: "#800000", name: "Maroon" },
  { code: "#8C001A", name: "Burgundy" },
  { code: "#7E191B", name: "Vermilion" },
  { code: "#800517", name: "Deep Red" },
  { code: "#660000", name: "Red Blood" },
  { code: "#551606", name: "Blood Night" },
  { code: "#560319", name: "Dark Scarlet" },
  { code: "#3D0C02", name: "Black Bean" },
  { code: "#3F000F", name: "Chocolate Brown" },
  { code: "#2B1B17", name: "Midnight" },
  { code: "#550A35", name: "Purple Lily" },
  { code: "#810541", name: "Purple Maroon" },
  { code: "#7D0541", name: "Plum Pie" },
  { code: "#7D0552", name: "Plum Velvet" },
  { code: "#872657", name: "Dark Raspberry" },
  { code: "#7E354D", name: "Velvet Maroon" },
  { code: "#7F4E52", name: "Rosy-Finch" },
  { code: "#7F525D", name: "Dull Purple" },
  { code: "#7F5A58", name: "Puce" },
  { code: "#997070", name: "Rose Dust" },
  { code: "#B1907F", name: "Pastel Brown" },
  { code: "#B38481", name: "Rosy Pink" },
  { code: "#BC8F8F", name: "RosyBrown" },
  { code: "#C5908E", name: "Khaki Rose" },
  { code: "#C48793", name: "Lipstick Pink" },
  { code: "#C48189", name: "Pink Brown" },
  { code: "#C08081", name: "Old Rose" },
  { code: "#D58A94", name: "Dusty Pink" },
  { code: "#E799A3", name: "Pink Daisy" },
  { code: "#E8ADAA", name: "Rose" },
  { code: "#C9A9A6", name: "Dusty Rose" },
  { code: "#C4AEAD", name: "Silver Pink" },
  { code: "#E6C7C2", name: "Gold Pink" },
  { code: "#ECC5C0", name: "Rose Gold" },
  { code: "#FFCBA4", name: "Deep Peach" },
  { code: "#F8B88B", name: "Pastel Orange" },
  { code: "#EDC9AF", name: "Desert Sand" },
  { code: "#FFDDCA", name: "Unbleached Silk" },
  { code: "#FDD7E4", name: "Pig Pink" },
  { code: "#F2D4D7", name: "Pale Pink" },
  { code: "#FFE6E8", name: "Blush" },
  { code: "#FFE4E1", name: "MistyRose" },
  { code: "#FFDFDD", name: "Pink Bubble Gum" },
  { code: "#FBCFCD", name: "Light Rose" },
  { code: "#FFCCCB", name: "Light Red" },
  { code: "#F6C6BD", name: "Warm Pink" },
  { code: "#FBBBB9", name: "Deep Rose" },
  { code: "#FFC0CB", name: "Pink" },
  { code: "#FFB6C1", name: "LightPink" },
  { code: "#FFB8BF", name: "Soft Pink" },
  { code: "#FAAFBE", name: "Donut Pink" },
  { code: "#FAAFBA", name: "Baby Pink" },
  { code: "#F9A7B0", name: "Flamingo Pink" },
  { code: "#FEA3AA", name: "Pastel Pink" },
  { code: "#E7A1B0", name: "Rose Pink or Pink Rose" },
  { code: "#E38AAE", name: "Cadillac Pink" },
  { code: "#F778A1", name: "Carnation Pink" },
  { code: "#E5788F", name: "Pastel Rose" },
  { code: "#E56E94", name: "Blush Red" },
  { code: "#DB7093", name: "PaleVioletRed" },
  { code: "#D16587", name: "Purple Pink" },
  { code: "#C25A7C", name: "Tulip Pink" },
  { code: "#C25283", name: "Bashful Pink" },
  { code: "#E75480", name: "Dark Pink" },
  { code: "#F660AB", name: "Dark Hot Pink" },
  { code: "#FF69B4", name: "HotPink" },
  { code: "#FC6C85", name: "Watermelon Pink" },
  { code: "#F6358A", name: "Violet Red" },
  { code: "#F52887", name: "Hot Deep Pink" },
  { code: "#FF007F", name: "Bright Pink" },
  { code: "#FF1493", name: "DeepPink" },
  { code: "#F535AA", name: "Neon Pink" },
  { code: "#FF33AA", name: "Chrome Pink" },
  { code: "#FD349C", name: "Neon Hot Pink" },
  { code: "#E45E9D", name: "Pink Cupcake" },
  { code: "#E759AC", name: "Royal Pink" },
  { code: "#E3319D", name: "Dimorphotheca Magenta" },
  { code: "#E4287C", name: "Pink Lemonade" },
  { code: "#FA2A55", name: "Red Pink" },
  { code: "#E30B5D", name: "Raspberry" },
  { code: "#DC143C", name: "Crimson" },
  { code: "#C32148", name: "Bright Maroon" },
  { code: "#C21E56", name: "Rose Red" },
  { code: "#C12869", name: "Rogue Pink" },
  { code: "#C12267", name: "Burnt Pink" },
  { code: "#CA226B", name: "Pink Violet" },
  { code: "#CC338B", name: "Magenta Pink" },
  { code: "#C71585", name: "MediumVioletRed" },
  { code: "#C12283", name: "Dark Carnation Pink" },
  { code: "#B3446C", name: "Raspberry Purple" },
  { code: "#B93B8F", name: "Pink Plum" },
  { code: "#DA70D6", name: "Orchid" },
  { code: "#DF73D4", name: "Deep Mauve" },
  { code: "#EE82EE", name: "Violet" },
  { code: "#FF77FF", name: "Fuchsia Pink" },
  { code: "#F433FF", name: "Bright Neon Pink" },
  { code: "#FF00FF", name: "Fuchsia or Magenta" },
  { code: "#E238EC", name: "Crimson Purple" },
  { code: "#D462FF", name: "Heliotrope Purple" },
  { code: "#C45AEC", name: "Tyrian Purple" },
  { code: "#BA55D3", name: "MediumOrchid" },
  { code: "#A74AC7", name: "Purple Flower" },
  { code: "#B048B5", name: "Orchid Purple" },
  { code: "#B666D2", name: "Rich Lilac" },
  { code: "#D291BC", name: "Pastel Violet" },
  { code: "#915F6D", name: "Mauve Taupe" },
  { code: "#7E587E", name: "Viola Purple" },
  { code: "#614051", name: "Eggplant" },
  { code: "#583759", name: "Plum Purple" },
  { code: "#5E5A80", name: "Grape" },
  { code: "#4E5180", name: "Purple Navy" },
  { code: "#6A5ACD", name: "SlateBlue" },
  { code: "#6960EC", name: "Blue Lotus" },
  { code: "#5865F2", name: "Blurple" },
  { code: "#736AFF", name: "Light Slate Blue" },
  { code: "#7B68EE", name: "MediumSlateBlue" },
  { code: "#7575CF", name: "Periwinkle Purple" },
  { code: "#6667AB", name: "Very Peri" },
  { code: "#6F2DA8", name: "Bright Grape" },
  { code: "#6C2DC7", name: "Purple Amethyst" },
  { code: "#6A0DAD", name: "Bright Purple" },
  { code: "#5453A6", name: "Deep Periwinkle" },
  { code: "#483D8B", name: "DarkSlateBlue" },
  { code: "#4E387E", name: "Purple Haze" },
  { code: "#571B7E", name: "Purple Iris" },
  { code: "#4B0150", name: "Dark Purple" },
  { code: "#36013F", name: "Deep Purple" },
  { code: "#2E1A47", name: "Midnight Purple" },
  { code: "#461B7E", name: "Purple Monster" },
  { code: "#4B0082", name: "Indigo" },
  { code: "#342D7E", name: "Blue Whale" },
  { code: "#663399", name: "RebeccaPurple" },
  { code: "#6A287E", name: "Purple Jam" },
  { code: "#8B008B", name: "DarkMagenta" },
  { code: "#800080", name: "Purple" },
  { code: "#86608E", name: "French Lilac" },
  { code: "#9932CC", name: "DarkOrchid" },
  { code: "#9400D3", name: "DarkViolet" },
  { code: "#8D38C9", name: "Purple Violet" },
  { code: "#A23BEC", name: "Jasmine Purple" },
  { code: "#B041FF", name: "Purple Daffodil" },
  { code: "#842DCE", name: "Clematis Violet" },
  { code: "#8A2BE2", name: "BlueViolet" },
  { code: "#7A5DC7", name: "Purple Sage Bush" },
  { code: "#7F38EC", name: "Lovely Purple" },
  { code: "#9D00FF", name: "Neon Purple" },
  { code: "#8E35EF", name: "Purple Plum" },
  { code: "#893BFF", name: "Aztech Purple" },
  { code: "#9370DB", name: "MediumPurple" },
  { code: "#8467D7", name: "Light Purple" },
  { code: "#9172EC", name: "Crocus Purple" },
  { code: "#9E7BFF", name: "Purple Mimosa" },
  { code: "#CCCCFF", name: "Periwinkle" },
  { code: "#DCD0FF", name: "Pale Lilac" },
  { code: "#967BB6", name: "Lavender Purple" },
  { code: "#B09FCA", name: "Rose Purple" },
  { code: "#C8A2C8", name: "Lilac" },
  { code: "#E0B0FF", name: "Mauve" },
  { code: "#D891EF", name: "Bright Lilac" },
  { code: "#C38EC7", name: "Purple Dragon" },
  { code: "#DDA0DD", name: "Plum" },
  { code: "#E6A9EC", name: "Blush Pink" },
  { code: "#F2A2E8", name: "Pastel Purple" },
  { code: "#F9B7FF", name: "Blossom Pink" },
  { code: "#C6AEC7", name: "Wisteria Purple" },
  { code: "#D2B9D3", name: "Purple Thistle" },
  { code: "#D8BFD8", name: "Thistle" },
  { code: "#DFD3E3", name: "Purple White" },
  { code: "#E9CFEC", name: "Periwinkle Pink" },
  { code: "#FCDFFF", name: "Cotton Candy" },
  { code: "#EBDDE2", name: "Lavender Pinocchio" },
  { code: "#E1D9D1", name: "Dark White" },
  { code: "#E9E4D4", name: "Ash White" },
  { code: "#EDE6D6", name: "White Chocolate" },
  { code: "#FAF0DD", name: "Soft Ivory" },
  { code: "#F8F0E3", name: "Off White" },
  { code: "#F8F6F0", name: "Pearl White" },
  { code: "#F3E8EA", name: "Red White" },
  { code: "#FFF0F5", name: "LavenderBlush" },
  { code: "#FDEEF4", name: "Pearl" },
  { code: "#FFF9E3", name: "Egg Shell" },
  { code: "#FEF0E3", name: "OldLace" },
  { code: "#FAF0E6", name: "Linen" },
  { code: "#FFF5EE", name: "SeaShell" },
  { code: "#F9F6EE", name: "Bone White" },
  { code: "#FAF5EF", name: "Rice" },
  { code: "#FFFAF0", name: "FloralWhite" },
  { code: "#FFFFF0", name: "Ivory" },
  { code: "#FFFFF4", name: "White Gold" },
  { code: "#FFFFF7", name: "Light White" },
  { code: "#F5F5F5", name: "WhiteSmoke" },
  { code: "#FBFBF9", name: "Cotton" },
  { code: "#FFFAFA", name: "Snow" },
  { code: "#FEFCFF", name: "Milk White" },
  { code: "#FFFEFA", name: "Half White" },
  { code: "#FFFFFF", name: "White" },
];
export default colorData;
